[platformio]
default_envs = esp8266-persiana-mqtt

[env:esp8266-persiana-mqtt]
platform = espressif8266
framework = arduino
board = d1_mini
monitor_speed = 115200
upload_port = /dev/cu.wchusbserial*
upload_protocol = esptool
lib_deps =
    bblanchon/ArduinoJson@^7.0.4
    knolleary/PubSubClient@^2.8
build_src_filter =
    +<app_esp8266_persiana_mqtt.cpp>
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DUSE_ESP8266_PERSIANA_MQTT
    -DMQTT_HOST=\"192.168.1.57\"
    -DMQTT_HOST_FALLBACK=\"192.168.1.34\"
    -DMQTT_PORT=1883
    -DMQTT_BASE_TOPIC=\"mini-has/devices\"

[env:esp8266-persiana-mqtt-ota]
extends = env:esp8266-persiana-mqtt
upload_protocol = espota
upload_port = persiana.local
